In [4]:
ls -l

total 37351220
-rw-rw-rw- 1 pipe11 pipe11      205272 Aug  1 13:33  02_ADSC_Exercise2.ipynb
-rw-rw-rw- 1 pipe11 pipe11      227479 Aug  1 20:05  04_ADSC_Exercise4.ipynb
-rw-rw-rw- 1 pipe11 pipe11       83001 Aug  2 10:54  18_TAC_Exercise4.ipynb
-rw-rw-rw- 1 pipe11 pipe11      748241 Jul 31 18:03  Corpus_spanish_train.xlsx
-rw-rw-rw- 1 pipe11 pipe11       51173 Aug  2 18:01 'Fake News.ipynb'
-rw-rw-rw- 1 pipe11 pipe11      114213 Aug  3 11:29  Fake_News_Spanish_Corpus.ipynb
-rw-rw-rw- 1 pipe11 pipe11        4184 Aug  2 17:12  Langdetect_filter.ipynb
-rw-rw-rw- 1 pipe11 pipe11       83699 Aug  3 12:58  News_big.ipynb
-rw-rw-rw- 1 pipe11 pipe11       88614 Aug  1 20:20 'Web Scraping CNMC-Copy1.ipynb'
-rw-rw-rw- 1 pipe11 pipe11    30696129 Jul 31 18:03  news.csv
-rw-rw-rw- 1 pipe11 pipe11 29322513705 Jul 31 19:59  news_cleaned_2018_02_13.csv
-rw-rw-rw- 1 pipe11 pipe11  8892759551 Aug  3 12:57  news_csv_filtered.csv

## Get familiar with data

Load with the csv in a DataFrame with nrows

Prepare the sample

In [130]:
import pandas as pd

df = pd.read_csv('news_csv_filtered.csv', sep = ',', nrows = 10000)

In [131]:
df.head()

,id,domain,type,url,content,title
0,22,theshovel.com.au,satire,http://www.theshovel.com.au/tag/malcolm-turnbu...,"For as long as he can remember, Malcolm Turnbu...",malcolm turnbull satire – The Shovel
1,23,theshovel.com.au,satire,http://www.theshovel.com.au/tag/malcolm-turnbu...,"For as long as he can remember, Malcolm Turnbu...",malcolm turnbull jokes – The Shovel
2,31,theshovel.com.au,satire,http://www.theshovel.com.au/tag/australian-pol...,Senators from the Australian Greens will be st...,Australian political satire – The Shovel
3,32,theshovel.com.au,satire,http://www.theshovel.com.au/tag/comedy-website...,Have you ever stopped and wondered what it wou...,comedy website australia – The Shovel
4,33,clickhole.com,satire,http://www.clickhole.com/article/serendipity-m...,"If you don’t believe in fate, here’s a story t...",Serendipity: This Man Made Up An Entire Person...

In [132]:
df.shape

(10000, 6)

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
id         10000 non-null int64
domain     10000 non-null object
type       10000 non-null object
url        10000 non-null object
content    10000 non-null object
title      10000 non-null object
dtypes: int64(1), object(5)
memory usage: 468.9+ KB

In [134]:
df.sample(10)

,id,domain,type,url,content,title
6058,15531,beforeitsnews.com,fake,http://beforeitsnews.com/space/2017/01/bullsey...,Bullseye: Amazing SpaceX Images Highlight Perf...,Bullseye: Amazing SpaceX Images Highlight Perf...
2808,8046,beforeitsnews.com,fake,http://beforeitsnews.com/gold-and-precious-met...,Breaking Down Bannon’s Betrayal Of Trump\n\nHe...,Breaking Down Bannon’s Betrayal Of Trump
7124,17582,beforeitsnews.com,fake,http://beforeitsnews.com/spirit/2016/12/a-chal...,A challenge to those that hope they have been ...,A challenge to those that hope they have been ...
2167,6471,beforeitsnews.com,fake,http://beforeitsnews.com/economy/2018/01/negat...,Negative 4.6% a Year – the Likely Seven-Year R...,Negative 4.6% a Year – the Likely Seven-Year R...
8078,19049,beforeitsnews.com,fake,http://beforeitsnews.com/prophecy/2015/10/2015...,2015 Sings Of The Reckoning Revelations The En...,2015 Sings Of The Reckoning Revelations The En...
9672,20990,beforeitsnews.com,fake,http://beforeitsnews.com/blogging-citizen-jour...,How To Easily Understand The Difference Betwee...,Bring Them Home: Trump Live Stream – Approx 2:...
4138,11467,beforeitsnews.com,fake,http://beforeitsnews.com/japan-earthquake/2017...,Radiation for Thousands of Years: Melted Fuel ...,Radiation for Thousands of Years: Melted Fuel ...
5946,15399,beforeitsnews.com,fake,http://beforeitsnews.com/alternative/2016/05/6...,6 Plants Other than Cannabis That are High in ...,6 Plants Other than Cannabis That are High in ...
5442,14493,beforeitsnews.com,fake,http://beforeitsnews.com/financial-markets/201...,"Halliburton Company, Netflix, gov’t shutdown a...","Halliburton Company, Netflix, gov’t shutdown a..."
2231,6638,beforeitsnews.com,fake,http://beforeitsnews.com/gold-and-precious-met...,The Census Bureau Advance Report on Internatio...,Trade Deficit Widens as Imports Rise More Than...

## Detect news in spanish language

We are going to use Langdetect package: https://pypi.org/project/langdetect/ to detect which news are in spanish and filter them.

Next step: Install the package, load it and test it

In [126]:
pip install langdetect

Collecting langdetect
Collecting six (from langdetect)
  Using cached https://files.pythonhosted.org/packages/ee/ff/48bde5c0f013094d729fe4b0316ba2a24774b3ff1c52d924a8a4cb04078a/six-1.15.0-py2.py3-none-any.whl
Installing collected packages: six, langdetect
Successfully installed langdetect-1.0.8 six-1.15.0
Note: you may need to restart the kernel to use updated packages.

In [135]:
from langdetect import detect
from langdetect import detect_langs

In [136]:
# Detect('String') -> It detects the language of the text. 'en' of english, 'es for spanish', etc.

# It only returns the top language in the text!! So if there is 70% text in spanish and 30% in english, it will return: 'es'

detect(df['content'].iloc[0])

'en'

In [137]:
# Detect_langs('String') -> It find out the probabilities for the top languages:

detect_langs(df['content'].iloc[0])

[en:0.9999976519658347]

# Testing with a loops over the df

Full text of the news are in the column 'content'

Test if there are news with 2 languages.

Finally detect which news are in spanish and load them in another DataFrame

### First iteration

1) We know there are news in spanish, so lets test how many are in a sample of 30000.

2) If there are news in spanish, print the row index.

3) Checkout the rows with news in spanish and lets see if there are 2 languages.

In [16]:
%%time

import pandas as pd
from langdetect import detect
from langdetect import detect_langs

count = 0

df = pd.read_csv('news_csv_filtered.csv', sep = ',', nrows = 20000)

for index, row in df.iterrows():
    if detect(row['content']) == 'es':
        count += 1
        langs = len(detect_langs(row['content'])) #Count the number of languages detected in the text
        print('The row %d has %d languages' % (index, langs))
    else:
        pass

print('There are %d news in spanish' % count)

The row 10895 has 2 languages
The row 17048 has 1 languages
The row 17049 has 1 languages
The row 17050 has 1 languages
The row 17051 has 1 languages
The row 17052 has 1 languages
The row 17053 has 1 languages
The row 17054 has 1 languages
The row 17055 has 1 languages
The row 17056 has 1 languages
The row 17057 has 1 languages
The row 17058 has 1 languages
The row 17059 has 1 languages
The row 17060 has 1 languages
The row 17061 has 1 languages
The row 17125 has 1 languages
The row 17216 has 1 languages
The row 17217 has 1 languages
The row 17361 has 1 languages
The row 17511 has 1 languages
The row 17530 has 1 languages
The row 17531 has 1 languages
The row 17532 has 1 languages
The row 17536 has 1 languages
The row 17537 has 1 languages
The row 17553 has 1 languages
The row 17559 has 1 languages
The row 17562 has 1 languages
The row 17564 has 1 languages
The row 17575 has 1 languages
The row 17576 has 1 languages
The row 17579 has 1 languages
The row 17580 has 1 languages
The row 17581 has 1 languages
The row 17582 has 1 languages
The row 17583 has 1 languages
The row 17584 has 1 languages
The row 17585 has 1 languages
The row 17586 has 1 languages
The row 17588 has 1 languages
The row 17589 has 1 languages
The row 17590 has 1 languages
The row 17591 has 1 languages
The row 17596 has 1 languages
The row 17599 has 1 languages
The row 17600 has 1 languages
The row 17601 has 1 languages
The row 17602 has 1 languages
The row 17603 has 1 languages
The row 17604 has 1 languages
The row 17605 has 1 languages
The row 17609 has 1 languages
The row 17611 has 1 languages
The row 17619 has 1 languages
The row 17620 has 1 languages
The row 17622 has 1 languages
The row 17623 has 1 languages
The row 17624 has 1 languages
The row 17625 has 1 languages
The row 17626 has 1 languages
The row 17627 has 1 languages
The row 17628 has 1 languages
The row 17629 has 1 languages
The row 17630 has 1 languages
The row 17631 has 1 languages
The row 17632 has 1 languages
The row 17633 has 1 languages
The row 17634 has 1 languages
The row 17635 has 1 languages
The row 17636 has 1 languages
The row 17637 has 1 languages
The row 17638 has 1 languages
The row 17639 has 1 languages
The row 17640 has 1 languages
The row 17644 has 1 languages
The row 17645 has 1 languages
The row 17646 has 1 languages
The row 17647 has 1 languages
The row 17648 has 1 languages
The row 17650 has 1 languages
The row 17651 has 1 languages
The row 17652 has 1 languages
The row 17653 has 1 languages
The row 17655 has 1 languages
The row 17656 has 1 languages
The row 17657 has 1 languages
The row 17668 has 1 languages
The row 17669 has 1 languages
The row 17670 has 1 languages
The row 17671 has 1 languages
The row 17672 has 1 languages
The row 17673 has 1 languages
The row 17674 has 1 languages
The row 17675 has 1 languages
The row 17676 has 1 languages
The row 17677 has 1 languages
The row 17678 has 1 languages
The row 17679 has 1 languages
The row 17682 has 1 languages
The row 17683 has 1 languages
The row 17684 has 1 languages
The row 17685 has 1 languages
The row 17686 has 1 languages
There are 103 news in spanish
CPU times: user 4min 1s, sys: 625 ms, total: 4min 1s
Wall time: 4min 2s

In [17]:
#Checking out the row 10895 with 2 languages

print(detect_langs(df['content'].iloc[10895]))

print(df['content'].iloc[10895])

[en:0.7142843867723477, es:0.285714276076371]
Breaking News: Massive police force Saturday, 16 arrests

Noticias de última hora: Fuerzas policiales masivas, 16 detenidos

North Dakota needs a lot of police to stop women and children from praying. Screen capture Censored News.

Excessive police force today to stop the prayer. Screen capture Censored News.

Screen capture video Censored News

.

Red Warrior Camp image

Sat. Oct. 15, 2016

Hundreds of water protectors walked in from several directions.

‘We walked two miles to support our warrior who is locked down.’

From legal team: Sixteen arrests in Morton County with charges mostly Disobedience of Public Safety Orders under Riot Conditions and Disorderly Cond uct, both class B misdemeanors, as well as criminal trespass and one new felony case. The water protector charged with a felony is in custody on a no bond hold. Six additional water protectors chose to spend the weekend in jail and will have bond hearings and arraignments on Monday.





By Brenda Norrell

Censored News

Oct. 15, 2016 update 8 p.m. today

ST. ANTHONY — More than 500 water protectors hiked to the sites of Dakota Access Pipeline construction and were met with massive police force and armored vehicles on Saturday. At least 16 water protectors were arrested, including one person who was locked down for five hours to equipment.

“We walked two miles to support our warrior who is locked down,” said one woman, among hundreds walking in from several directions.

Water protectors reported seeing the National Guard arrive near the site where the water protector was locked down to a track hoe.

Joye said, “Started the morning before the sun rose above the eastern horizon with prayers in a circle of water protectors and land defenders. That is the best feeling in the world. The morning progressed with a helicopter flying overhead, a line of cars stretching behind and in front of us. Each person dedicated to protecting the Sacred.

“Prayers, water and tobacco offered to the police to let us pray. The police moved back some and people walked over the hill to offer their prayers.

Joye, describing the pain from medical shots to her knees, said, “My knees are hurting still from the shots, so I came back to help be rear guard.”

“Police have cars on all the roads leading to where we are and have blocked off those who walked to pray.”

“We are waiting to see if we can get our prayer warriors back safe and get us out safe. In another action away from here 10 were arrested,” Joye said.

“DAPL workers were conveyed out of the construction site by bus.”

“Right now I’m looking at four police cruisers, Fargo police, ahead of me about an 1/8 of a mile away. We continue to pray we continue to stand. We stand,” Joye said.

Melissa said, “The cops made a barricade. We sang, prayed, and marched right past them on to shut down the work site. Coming from three directions. Hundreds of us; using their tactics against them. We marched 3 miles so far. Pushed them back mile by mile. There are people locked down to the machinery on the site. Headed to them. Send all the love.”



Open records request shows that for North Dakota and Morton Co., it is all about the money

The live streamers Unicorn Riot filed a public records request. The records show that for North Dakota and Morton Co., it is all about the money.

The state and police use tactics of over-policing and frightening the public. The state and Morton Co. are the only ones attempting to incite a riot.

Live streamers of Unicorn Riot are among the media who have been arrested and jailed by these police violating human rights and civil rights. Morton Co. doesn’t want the public to see the truth revealed in the live streams, so police are arresting the media.

The truth is that Native Americans are facing armored vehicles and loaded assault weapons as they pray.

See Unicorn Riot records request revealing for North Dakota and police, it is all a about the money: http://www.unicornriot.ninja/?p=9638



Noticias de última hora: Fuerzas policiales masivas, 16 detenidos Cientos de protectores del agua entraron desde varias direcciones. “Caminamos dos millas para apoyar nuestro guerrero que está encadenado. “ Desde el equipo legal: Dieciséis detenciones en el condado de Morton con cargos, sobre todo, relacionados con la desobediencia a las órdenes de la seguridad pública antidisturbios, condiciones y conducta desordenada, ambos delitos menores de clase B, así como la entrada ilegal y un caso nuevo de delito grave. El protector del agua que tenía un delito grave, se encuentra detenido sin derecho a fianza. Seis protectores adicionales de agua eligieron pasar el fin de semana en la cárcel y tendrán audiencias de fianza y de lectura de cargos el lunes. Por Brenda Norrell Censored News 15 de Oct., el año 2016 al día de hoy 8 p.m. Villanueva, S. (Traducción) ST. ANTHONY – Más de 500 protectores del agua se metieron a los sitios de construcción del oleoducto Acceso a Dakota de la petrolera y se encontraron con la fuerza masiva de la policía y vehículos blindados el sábado. Al menos 16 protectores del agua fueron detenidas, entre ellos una persona que se había encadenado durante cinco horas a los equipos de construcción. “Caminamos dos millas para apoyar a nuestro guerrero que está encadenado”, dijo una mujer, entre cientos caminando desde varias direcciones. Los protectores del agua reportaron haber visto a la Guardia Nacional que llegaba cerca del lugar donde el protector del agua estaba encadenado a una maquinaria de construcción. Joye dijo, “Se empezó por la mañana antes de que saliera el sol sobre el horizonte oriental, con oraciones en un círculo de protectores del agua y los defensores de la tierra. Esa es la mejor sensación del mundo. La mañana transcurrió con un helicóptero que volaba por encima, una fila de coches que se alargaba detrás y delante de nosotros. Cada persona dedicada a la protección de lo Sagrado.” “Las oraciones, el agua y el tabaco fueron ofrecidos a la policía para que oremos. La policía regreso a algunos y la gente caminaba sobre la colina para ofrecer sus oraciones.” Joye, que describe el dolor de las inyecciones médicas a sus rodillas, dijo: “Mis rodillas están sufriendo todavía de las inyecciones, por lo que regresó a ayudar a la retaguardia.” “La policía tiene coches en todos los caminos que conducen a dónde estamos y han bloqueado los que desean caminar para orar.” “Estamos a la espera de ver si podemos conseguir nuestros guerreros de la oración de vuelta sanos y salvos. En otra acción de aquí 10 fueron detenidos,” dijo Joye. “Los trabajadores de DAPL (el oleoducto Acceso a Dakota, por sus siglas en inglés) se transportaron fuera del emplazamiento de la obra en autobús.” “En este momento estoy mirando a cuatro coches de policía. La policía de Fargo, delante de mí, esta sobre un 1/8 de milla de distancia. Seguimos orando seguimos de pie. Estamos aquí”, dijo Joye. Melissa dijo: “Los policías hicieron una barricada, cantamos, oramos, y marchamos a la derecha más allá de ellos para cerrar el sitio de trabajo. Llegamos desde tres direcciones, cientos de nosotros. Utilizamos sus propias tácticas contra ellos. Marchamos 3 millas hasta el momento. Los empujamos hacia atrás milla tras milla. Hay personas encadenadas a la maquinaria en el lugar de la construcción. Nos dirigimos a ellos. Envíenos todo su amor. “ Las solicitudes de acceso transparente a la información, muestran que para Dakota del Norte y Morton Co., todo tiene que ver con el dinero.

Los transmisores en vivo en las redes sociales, autodenominados “Unicornios antidisturbios” (Unicorn Riot) presentaron una solicitud de registros públicos. Los registros muestran que para el estado de Dakota del Norte y el condado de Morton todo tiene que ver con el dinero. Las tácticas de fuerza excesiva de la policía del estado y el uso de un exceso de vigilancia sirven para aterrorizar al público. El estado y Morton Co. son los únicos que tratan de incitar a una revuelta. Los transmisores en vivo en las redes sociales de “Unicornios antidisturbios” son algunos de los medios que han sido detenidos y encarcelados por estos agentes que violan los derechos humanos y los derechos civiles. Morton Co. no quiere que el público vea la verdad revelada en las transmisiones en vivo, por lo que la policía está deteniendo a los medios de comunicación. La verdad es que los pueblos originarios de Norteamérica se enfrentan a los vehículos blindados y armas de asalto cargadas mientras rezan. Vea los registros de Unicornio antidisturbios solicitados que revelan porque el estado de Dakota del Norte y de la policía, solo les interesa el dinero: http://www.unicornriot.ninja/? p=9638

Photo by Tara

### Next iterations

1) There are news in spanish, but sometimes mixed with news in english.

2) We only want full news in spanish, so we need to filter them.

3) Build another DataFrame with news in spanish or drop the english or mixed one.

4) Test differents loops: We need the most efficient and fastest way to work later with big data.

### #Code1: With iterrows and dropping the rows that don't have news in spanish language and have more than one language

In [42]:
%%time

df_esp1 = pd.read_csv('news_csv_filtered.csv', sep = ',', nrows = 20000)

for index, row in df_esp1.iterrows():
    # Detect if the news are in spanish and only those with one language detected
    if not(detect(row['content']) == 'es' and len(detect_langs(row['content'])) == 1):
        df_esp1.drop(index, inplace = True)
    else:
        pass

CPU times: user 4min 33s, sys: 688 ms, total: 4min 34s
Wall time: 4min 34s

In [43]:
df_esp1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102 entries, 17048 to 17686
Data columns (total 6 columns):
id         102 non-null int64
domain     102 non-null object
type       102 non-null object
url        102 non-null object
content    102 non-null object
title      102 non-null object
dtypes: int64(1), object(5)
memory usage: 5.6+ KB

### #2 Code:  With iterrows, appending rows with news in spanish in a list, and finally create a new DataFrame

In [59]:
%%time

row_esp = []

df = pd.read_csv('news_csv_filtered.csv', sep = ',', nrows = 20000)

for index, row in df.iterrows():
    # Detect if the news are in spanish and only those with one language detected
    if detect(row['content']) == 'es' and len(detect_langs(row['content'])) == 1:
        row_esp.append(row.values)
    else:
        pass

df_esp2 = pd.DataFrame(row_esp, columns = df.columns)

CPU times: user 3min 54s, sys: 391 ms, total: 3min 54s
Wall time: 3min 54s

In [60]:
df_esp2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 6 columns):
id         102 non-null int64
domain     102 non-null object
type       102 non-null object
url        102 non-null object
content    102 non-null object
title      102 non-null object
dtypes: int64(1), object(5)
memory usage: 4.9+ KB

In [61]:
df_esp2.head()

,id,domain,type,url,content,title
0,30301,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/allanada...,Esta mañana unidades del CTI allanaron las ofi...,Allanadas oficinas de Actualidad Panamericana ...
1,30303,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/ya-abrie...,Algo de sosiego trajo a los miles de viajeros ...,Ya abrieron un D1 en trancón de La Línea
2,30304,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/jaguares...,El fin de año es época de anuncios en el fútbo...,Jaguares anunció a Dimayor como patrocinador p...
3,30305,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/embajado...,Un mico de última hora en la nueva ley que rig...,"Embajadora de Florhuila, Claudia Bahamón defie..."
4,30348,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/guia-inv...,Cada nuevo año es la oportunidad para planear ...,Guía para invertir su dinero en 2018

### #3 Code:  Without iterrows, appending each value in a list, create a new DataFrame with all the lists created.

In [24]:
%%time

id_list = []
type_list = []
title_list = []
content_list = []
url_list = []
domain_list = []

num = 20000

df = pd.read_csv('news_csv_filtered.csv', sep = ',', nrows = num)

for n in range(num):
    if detect(df['content'].iloc[n]) == 'es' and len(detect_langs(df['content'].iloc[n])) == 1:
        content_list.append(df['content'].iloc[n])
        id_list.append(df['id'].iloc[n])
        type_list.append(df['type'].iloc[n])
        title_list.append(df['title'].iloc[n])
        url_list.append(df['url'].iloc[n])
        domain_list.append(df['domain'].iloc[n])
    else:
        pass

df_esp3 = pd.DataFrame({
    'id': id_list,
    'type': type_list,
    'domain': domain_list,
    'title': title_list ,
    'content': content_list,
    'url': url_list
    })

CPU times: user 3min 46s, sys: 1.84 s, total: 3min 48s
Wall time: 3min 48s

In [25]:
df_esp3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 6 columns):
id         102 non-null int64
type       102 non-null object
domain     102 non-null object
title      102 non-null object
content    102 non-null object
url        102 non-null object
dtypes: int64(1), object(5)
memory usage: 4.9+ KB

# Adjust the code to work with Big Data

1) Define chunksize and try a simple loop

2) Try the 3 loops with chunks and find which method is the most efficient and fastest

3) Launch the final code without nrows

In [82]:
%%time

df = pd.read_csv('news_csv_filtered.csv', sep = ',', chunksize = 100000)

for i, chunk in enumerate(df):
    print('Processing chunk %d with %d longitude.' %(i, len(chunk)))
    print(chunk.info())

Processing chunk 0 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 1 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 100000 to 199999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 2 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 200000 to 299999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 3 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 300000 to 399999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 4 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 400000 to 499999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 5 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 500000 to 599999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 6 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 600000 to 699999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 7 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 700000 to 799999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 8 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 800000 to 899999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 9 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 900000 to 999999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 10 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1000000 to 1099999
Data columns (total 6 columns):
id         99999 non-null float64
domain     100000 non-null object
type       100000 non-null object
url        99999 non-null object
content    99998 non-null object
title      99998 non-null object
dtypes: float64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 11 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1100000 to 1199999
Data columns (total 6 columns):
id         99997 non-null float64
domain     100000 non-null object
type       100000 non-null object
url        99997 non-null object
content    99994 non-null object
title      99994 non-null object
dtypes: float64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 12 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1200000 to 1299999
Data columns (total 6 columns):
id         99999 non-null float64
domain     100000 non-null object
type       100000 non-null object
url        99999 non-null object
content    99998 non-null object
title      99998 non-null object
dtypes: float64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 13 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1300000 to 1399999
Data columns (total 6 columns):
id         99992 non-null float64
domain     100000 non-null object
type       100000 non-null object
url        99992 non-null object
content    99984 non-null object
title      99984 non-null object
dtypes: float64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 14 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1400000 to 1499999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 15 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1500000 to 1599999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 16 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1600000 to 1699999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 17 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1700000 to 1799999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 18 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1800000 to 1899999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 19 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1900000 to 1999999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None

Processing chunk 20 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2000000 to 2099999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 21 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2100000 to 2199999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 22 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2200000 to 2299999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 23 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2300000 to 2399999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 24 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2400000 to 2499999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 25 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2500000 to 2599999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 26 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2600000 to 2699999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 27 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2700000 to 2799999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 28 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2800000 to 2899999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 29 with 20637 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20637 entries, 2900000 to 2920636
Data columns (total 6 columns):
id         20637 non-null int64
domain     20637 non-null object
type       20637 non-null object
url        20637 non-null object
content    20637 non-null object
title      20637 non-null object
dtypes: int64(1), object(5)
memory usage: 967.5+ KB
None
CPU times: user 1min 3s, sys: 12.2 s, total: 1min 15s
Wall time: 1min 15s

### Error:

Chunks 10 to 13, those included, sometimes thye have missing rows in all columns except the columns 'type' and 'domain'.
It could be because there are a lot \n in the text.

### Anyways it can be solved loading the whole df with the parameter *lineterminator = '\n'*

In [85]:
%%time

df = pd.read_csv('news_csv_filtered.csv', sep = ',', lineterminator = '\n', chunksize = 100000)

for i, chunk in enumerate(df):
    print('Processing chunk %d with %d longitude.' %(i, len(chunk)))
    print(chunk.info())

Processing chunk 0 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 1 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 100000 to 199999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 2 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 200000 to 299999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 3 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 300000 to 399999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 4 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 400000 to 499999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 5 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 500000 to 599999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 6 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 600000 to 699999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 7 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 700000 to 799999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 8 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 800000 to 899999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 9 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 900000 to 999999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 10 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1000000 to 1099999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 11 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1100000 to 1199999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 12 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1200000 to 1299999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 13 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1300000 to 1399999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 14 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1400000 to 1499999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 15 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1500000 to 1599999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 16 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1600000 to 1699999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 17 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1700000 to 1799999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 18 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1800000 to 1899999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 19 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 1900000 to 1999999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None

Processing chunk 20 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2000000 to 2099999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 21 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2100000 to 2199999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 22 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2200000 to 2299999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 23 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2300000 to 2399999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 24 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2400000 to 2499999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 25 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2500000 to 2599999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 26 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2600000 to 2699999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 27 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2700000 to 2799999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 28 with 100000 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 2800000 to 2899999
Data columns (total 6 columns):
id         100000 non-null int64
domain     100000 non-null object
type       100000 non-null object
url        100000 non-null object
content    100000 non-null object
title      100000 non-null object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB
None
Processing chunk 29 with 20624 longitude.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20624 entries, 2900000 to 2920623
Data columns (total 6 columns):
id         20624 non-null int64
domain     20624 non-null object
type       20624 non-null object
url        20624 non-null object
content    20624 non-null object
title      20624 non-null object
dtypes: int64(1), object(5)
memory usage: 966.9+ KB
None
CPU times: user 1min 1s, sys: 12.3 s, total: 1min 13s
Wall time: 1min 14s

## Now lets adjust the code to filter the news in spanish with chunks:

### #1 Code with chunks

In [95]:
%%time

df = pd.read_csv('news_csv_filtered.csv', sep = ',', lineterminator = '\n', nrows = 20000, chunksize = 1000)

all_chunks1 = pd.DataFrame()

for i, chunk in enumerate(df):
    print(i, len(chunk))

    for index, row in chunk.iterrows():
        if not(detect(row['content']) == 'es' and len(detect_langs(row['content'])) == 1):
            chunk.drop(index, inplace = True)
        else:
            pass
    
    all_chunks1 = all_chunks1.append(chunk)

0 1000
1 1000
2 1000
3 1000
4 1000
5 1000
6 1000
7 1000
8 1000
9 1000
10 1000
11 1000
12 1000
13 1000
14 1000
15 1000
16 1000
17 1000
18 1000
19 1000
CPU times: user 4min 21s, sys: 703 ms, total: 4min 22s
Wall time: 4min 22s

In [97]:
all_chunks1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102 entries, 17048 to 17686
Data columns (total 6 columns):
id         102 non-null int64
domain     102 non-null object
type       102 non-null object
url        102 non-null object
content    102 non-null object
title      102 non-null object
dtypes: int64(1), object(5)
memory usage: 5.6+ KB

In [98]:
all_chunks1.head()

,id,domain,type,url,content,title
17048,30301,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/allanada...,Esta mañana unidades del CTI allanaron las ofi...,Allanadas oficinas de Actualidad Panamericana ...
17049,30303,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/ya-abrie...,Algo de sosiego trajo a los miles de viajeros ...,Ya abrieron un D1 en trancón de La Línea
17050,30304,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/jaguares...,El fin de año es época de anuncios en el fútbo...,Jaguares anunció a Dimayor como patrocinador p...
17051,30305,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/embajado...,Un mico de última hora en la nueva ley que rig...,"Embajadora de Florhuila, Claudia Bahamón defie..."
17052,30348,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/guia-inv...,Cada nuevo año es la oportunidad para planear ...,Guía para invertir su dinero en 2018

### #2 Code with chunks

In [99]:
%%time

row_esp = []

df = pd.read_csv('news_csv_filtered.csv', sep = ',', lineterminator = '\n', nrows = 20000, chunksize = 1000)

for i, chunk in enumerate(df):
    print(i, len(chunk))

    for index, row in chunk.iterrows():
        if detect(row['content']) == 'es' and len(detect_langs(row['content'])) == 1:
            row_esp.append(row.values)
        else:
            pass

all_chunks2 = pd.DataFrame(row_esp, columns = chunk.columns)

0 1000
1 1000
2 1000
3 1000
4 1000
5 1000
6 1000
7 1000
8 1000
9 1000
10 1000
11 1000
12 1000
13 1000
14 1000
15 1000
16 1000
17 1000
18 1000
19 1000
CPU times: user 4min 8s, sys: 656 ms, total: 4min 9s
Wall time: 4min 9s

In [101]:
all_chunks2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 6 columns):
id         102 non-null int64
domain     102 non-null object
type       102 non-null object
url        102 non-null object
content    102 non-null object
title      102 non-null object
dtypes: int64(1), object(5)
memory usage: 4.9+ KB

In [102]:
all_chunks2.head()

,id,domain,type,url,content,title
0,30301,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/allanada...,Esta mañana unidades del CTI allanaron las ofi...,Allanadas oficinas de Actualidad Panamericana ...
1,30303,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/ya-abrie...,Algo de sosiego trajo a los miles de viajeros ...,Ya abrieron un D1 en trancón de La Línea
2,30304,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/jaguares...,El fin de año es época de anuncios en el fútbo...,Jaguares anunció a Dimayor como patrocinador p...
3,30305,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/embajado...,Un mico de última hora en la nueva ley que rig...,"Embajadora de Florhuila, Claudia Bahamón defie..."
4,30348,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/guia-inv...,Cada nuevo año es la oportunidad para planear ...,Guía para invertir su dinero en 2018

### #3 Code with chunks

In [103]:
%%time

id_list = []
type_list = []
domain_list = []
title_list = []
content_list = []
url_list = []

df = pd.read_csv('news_csv_filtered.csv', sep = ',', lineterminator = '\n', nrows = 20000, chunksize = 1000)

for i, chunk in enumerate(df):
    print(i, len(chunk))
    num = len(chunk.index)

    for n in range(num):
        if detect(chunk['content'].iloc[n]) == 'es' and len(detect_langs(chunk['content'].iloc[n])) == 1:
            id_list.append(chunk['id'].iloc[n])
            type_list.append(chunk['type'].iloc[n])
            domain_list.append(chunk['domain'].iloc[n])
            title_list.append(chunk['title'].iloc[n])            
            content_list.append(chunk['content'].iloc[n])
            url_list.append(chunk['url'].iloc[n])
        else:
            pass

all_chunks3 = pd.DataFrame({
    'id': id_list,
    'type': type_list,
    'domain': domain_list,
    'title': title_list ,
    'content' : content_list,
    'url' : url_list,
    })

0 1000
1 1000
2 1000
3 1000
4 1000
5 1000
6 1000
7 1000
8 1000
9 1000
10 1000
11 1000
12 1000
13 1000
14 1000
15 1000
16 1000
17 1000
18 1000
19 1000
CPU times: user 4min 3s, sys: 531 ms, total: 4min 3s
Wall time: 4min 4s

In [93]:
all_chunks3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 6 columns):
id         103 non-null int64
type       103 non-null object
domain     103 non-null object
title      103 non-null object
content    103 non-null object
url        103 non-null object
dtypes: int64(1), object(5)
memory usage: 5.0+ KB

In [94]:
all_chunks3.head()

,id,type,domain,title,content,url
0,22403,fake,beforeitsnews.com,Standing Rock: 16 Water Protectors Arrested Oc...,"Breaking News: Massive police force Saturday, ...",http://beforeitsnews.com/native-american-news/...
1,30301,satire,actualidadpanamericana.com,Allanadas oficinas de Actualidad Panamericana ...,Esta mañana unidades del CTI allanaron las ofi...,http://www.actualidadpanamericana.com/allanada...
2,30303,satire,actualidadpanamericana.com,Ya abrieron un D1 en trancón de La Línea,Algo de sosiego trajo a los miles de viajeros ...,http://www.actualidadpanamericana.com/ya-abrie...
3,30304,satire,actualidadpanamericana.com,Jaguares anunció a Dimayor como patrocinador p...,El fin de año es época de anuncios en el fútbo...,http://www.actualidadpanamericana.com/jaguares...
4,30305,satire,actualidadpanamericana.com,"Embajadora de Florhuila, Claudia Bahamón defie...",Un mico de última hora en la nueva ley que rig...,http://www.actualidadpanamericana.com/embajado...

## Launch the final code

There is not fastest way, they are both pretty similar, so we are using the #2 code because it has less code and the #1 without chunks was the slowlest.

Now we launch the final code without nrows limit and lets hope it works well without any error. 

Langdetect package can experiments difficulties if a row lacks text or only includes symbols/numbers, even if they are string type.

In [105]:
%%time

import pandas as pd
from langdetect import detect
from langdetect import detect_langs
from datetime import datetime

row_spanish = []

df = pd.read_csv('news_csv_filtered.csv', sep = ',', lineterminator = '\n', chunksize = 100000)

for i, chunk in enumerate(df):
    print("Start with chunk %d : %d at %s" % (i, len(chunk), datetime.now()))

    for index, row in chunk.iterrows():
        if detect(row['content']) == 'es' and len(detect_langs(row['content'])) == 1:
            row_spanish.append(row.values)
        else:
            pass

df_spanish = pd.DataFrame(row_spanish, columns = chunk.columns)

Start with chunk 0 : 100000 at 2020-08-04 16:47:15.760160
Start with chunk 1 : 100000 at 2020-08-04 17:05:05.549365
Start with chunk 2 : 100000 at 2020-08-04 17:20:40.028981
Start with chunk 3 : 100000 at 2020-08-04 17:37:49.118225
Start with chunk 4 : 100000 at 2020-08-04 17:54:17.801163
Start with chunk 5 : 100000 at 2020-08-04 18:08:37.208716
Start with chunk 6 : 100000 at 2020-08-04 18:22:42.874893
Start with chunk 7 : 100000 at 2020-08-04 18:35:52.347911
Start with chunk 8 : 100000 at 2020-08-04 18:51:30.027157
Start with chunk 9 : 100000 at 2020-08-04 19:07:39.723881
Start with chunk 10 : 100000 at 2020-08-04 19:24:18.425313
Start with chunk 11 : 100000 at 2020-08-04 19:40:40.202050

LangDetectException: No features in text.

## Got an error at chunk 12: 'No features in text'

The error comes from the langdetect package. It can't extract features from a row on the 'content' column.

So from row 1200000 there are rows with any error, a row with 'content' column without text or with symbols.

Lets check it out, with skiprows to the 1200000 row, and keep doing the chunksize loop to find the exact row.

## Update

The row index is: 1223598

I went back to the previous notebook to drop that row and to export again the csv.

# Now we can run it without any problem!

In [1]:
%%time

import pandas as pd
from langdetect import detect
from langdetect import detect_langs
from datetime import datetime

row_spanish = []

df = pd.read_csv('news_csv_filtered.csv', sep = ',', lineterminator = '\n', skiprows = range(1,1100000), chunksize = 100000)

for i, chunk in enumerate(df):
    print("Start with chunk %d : %d at %s" % (i, len(chunk), datetime.now()))

    for index, row in chunk.iterrows():
        if detect(row['content']) == 'es' and len(detect_langs(row['content'])) == 1:
            row_spanish.append(row.values)
        else:
            pass

df_spanish = pd.DataFrame(row_spanish, columns = chunk.columns)

Start with chunk 0 : 100000 at 2020-08-05 12:08:23.422364
Start with chunk 1 : 100000 at 2020-08-05 12:25:59.846443
Start with chunk 2 : 100000 at 2020-08-05 12:40:47.514346

LangDetectException: No features in text.

In [32]:
%%time

import pandas as pd
from langdetect import detect
from langdetect import detect_langs
from datetime import datetime

row_spanish = []

df = pd.read_csv('news_csv_filtered.csv', sep = ',', lineterminator = '\n', chunksize = 100000)

for i, chunk in enumerate(df):
    print("Start with chunk %d : %d at %s" % (i, len(chunk), datetime.now()))

    for index, row in chunk.iterrows():
        if detect(row['content']) == 'es' and len(detect_langs(row['content'])) == 1:
            row_spanish.append(row.values)
        else:
            pass

df_spanish = pd.DataFrame(row_spanish, columns = chunk.columns)

Start with chunk 0 : 100000 at 2020-08-05 18:18:05.471322
Start with chunk 1 : 100000 at 2020-08-05 18:33:47.172801
Start with chunk 2 : 100000 at 2020-08-05 18:47:21.304434
Start with chunk 3 : 100000 at 2020-08-05 19:03:27.036702
Start with chunk 4 : 100000 at 2020-08-05 19:18:51.819290
Start with chunk 5 : 100000 at 2020-08-05 19:33:11.387865
Start with chunk 6 : 100000 at 2020-08-05 19:47:52.917880
Start with chunk 7 : 100000 at 2020-08-05 20:00:12.873852
Start with chunk 8 : 100000 at 2020-08-05 20:13:58.912623
Start with chunk 9 : 100000 at 2020-08-05 20:28:55.539093
Start with chunk 10 : 100000 at 2020-08-05 20:43:40.334156
Start with chunk 11 : 100000 at 2020-08-05 20:58:57.674161
Start with chunk 12 : 100000 at 2020-08-05 21:13:39.555925
Start with chunk 13 : 100000 at 2020-08-05 21:28:36.312966
Start with chunk 14 : 100000 at 2020-08-05 21:43:51.850637
Start with chunk 15 : 100000 at 2020-08-05 21:59:18.903788
Start with chunk 16 : 100000 at 2020-08-05 22:13:56.803893
Start with chunk 17 : 100000 at 2020-08-05 22:28:33.132088
Start with chunk 18 : 100000 at 2020-08-05 22:43:11.403924
Start with chunk 19 : 100000 at 2020-08-05 22:58:09.785489
Start with chunk 20 : 100000 at 2020-08-05 23:13:29.445077
Start with chunk 21 : 100000 at 2020-08-05 23:28:50.378262
Start with chunk 22 : 100000 at 2020-08-05 23:44:11.721338
Start with chunk 23 : 100000 at 2020-08-06 00:00:00.159865
Start with chunk 24 : 100000 at 2020-08-06 00:15:47.441765
Start with chunk 25 : 100000 at 2020-08-06 00:32:00.726028
Start with chunk 26 : 100000 at 2020-08-06 00:49:29.423608
Start with chunk 27 : 100000 at 2020-08-06 01:06:39.340321
Start with chunk 28 : 100000 at 2020-08-06 01:24:53.172731
Start with chunk 29 : 20621 at 2020-08-06 01:45:52.062562
CPU times: user 7h 22min 19s, sys: 9min 53s, total: 7h 32min 12s
Wall time: 7h 32min 32s

In [34]:
df_spanish.to_csv('news_csv_spanish.csv', sep = ',', index = False)

In [33]:
df_spanish.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4612 entries, 0 to 4611
Data columns (total 6 columns):
id         4612 non-null int64
domain     4612 non-null object
type       4612 non-null object
url        4612 non-null object
content    4612 non-null object
title      4612 non-null object
dtypes: int64(1), object(5)
memory usage: 216.3+ KB

In [30]:
detect_langs(df_spanish['content'].iloc[0])

[es:0.9999950854264592]

In [40]:
df_spanish.groupby('type').size().sort_values(ascending = False)

type
reliable    3164
satire      1323
fake         125
dtype: int64

In [84]:
df_spanish[df_spanish['type'] == 'satire'].sample(10)

,id,domain,type,url,content,title
1616,2738487,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/derechis...,Según un estudio realizado por investigadores ...,Derechismo tardío en personas mayores sería re...
2069,2741521,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/pedialyt...,Llega el fin de semana y millones en nuestro p...,"Pedialyte lanza sabor “Cacique”, producto espe..."
21,31684,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/colombia...,"“Feliz, definitivamente feliz, un orgullo para...",Colombiano del sur de la Florida quiere ser “p...
1409,2737376,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/juan-man...,"En la recta final de una campaña que, contra t...","Juan Manuel Santos asegura que si hay paz, se ..."
4515,7602636,elmundotoday.com,satire,http://www.elmundotoday.com/2009/03/ser-minima...,Algunos críticos dicen que es el máximo repres...,"“Ser minimalista es cagar de pie, sin artificios”"
1130,2733890,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/camiseta...,Fin del misterio. Actualidad Panamericana cono...,Camiseta Adidas de Colombia en Rusia 2018 será...
1611,2738462,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/joven-no...,"Ungenio Rodríguez, joven de 16 años, resultó q...",Joven que no usa pólvora se quema con un buñuelo
2031,2740770,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/jose-fel...,Luego de la polémica levantada por los gestos ...,José Feliciano dice que las bogotanas son las ...
2283,2744351,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/richard-...,Conocido en todo el planeta por su inigualable...,Richard Branson incursiona en negocio de fotom...
2114,2742952,actualidadpanamericana.com,satire,http://www.actualidadpanamericana.com/mujer-co...,"Tatiana Castañeda, una hermosa caleña, terminó...",Mujer consigue hombre de verdad mientras su es...

In [73]:
df_spanish[df_spanish['type'] == 'fake'].iloc[104]

id                                                   7079332
domain                                     beforeitsnews.com
type                                                    fake
url        http://beforeitsnews.com/politics/2015/01/ataq...
content    Ataque Terrorista en París no es consecuencia ...
title      Ataque Terrorista en París no es consecuencia ...
Name: 4491, dtype: object

In [77]:
df_spanish['content'][df_spanish['type'] == 'fake'].iloc[108]

"“Propaganda” y “relaciones sociales” : Guerra y Estado Policial.\n\n% of readers think this story is Fact. Add your two cents.\n\n(Before It's News)\n\nEl título más apropiado debería haber sido: Técnicas de propaganda modernas utilizadas por el Estado corporativo para hacer cumplir las políticas anti-democráticas y destructivas que implican habitualmente la fabricación y manipulación de los hechos noticiosos para moldear la opinión pública y, de cómo Edward Bernays usó la “ingeniería del consentimiento” para ciertos fines, pero bueno, el elegido creo que resume esquemáticamente lo que quiero explicar.\n\nTales eventos incluyen no sólo las abiertas apelaciones políticas, sino también los actos de terrorismo aparentemente espontáneo y el militarismo que traumatiza el cuerpo político en última instancia y la aceptación de las narraciones falsas como las realidades políticas e históricas. Un ejemplo lo tenemos con Woodrow Wilson, que sumió a los Estados Unidos en la guerra más violenta y homicida de la historia humana. Wilson, un ex académico de la Universidad de Princeton, preparado para un cargo público por los banqueros de Wall Street, reunió a un grupo de periodistas y publicistas “progres” para que “vendiera la guerra” al pueblo estadounidense.\n\nGeorge Creel, Walter Lippmann, Edward Bernays y Harold Lasswell. Todos desempeñaron papeles influyentes en el recién formado Comité de Información Pública (Committee on Public Information / CPI), y pasaría a tener en sus filas figuras importantes en el pensamiento político, en las relaciones públicas y en la investigación de la guerra psicológica.\n\nEl CPI no sólo fue capaz de censurar oficialmente noticias e información, sino que también los fabricó. Actuando en el papel de una agencia de publicidad multifacética, la operación Creel “examinó las diferentes maneras en que la información fluía a la población e inundó estos canales con material de pro-guerra”.\n\nEl órgano interno del Comité se compone de 19 subdivisiones, cada uno dedicado a un tipo específico de propaganda, uno de los cuales era una división de News que distribuye más de 6.000 notas de prensa y actuó como la principal corriente de información relacionadas con la guerra. El promedio en una semana era más de 20.000 columnas periodísticas con datos proporcionados a través de la propaganda del CPI. La División de Sindicated Features contó con la ayuda de los novelistas populares, cuentistas y ensayistas. Estos principales autores estadounidenses presentaron la línea oficial en una forma fácilmente accesible alcanzando a doce millones de personas cada mes. Esfuerzos similares existieron para el cine, la oratoria improvisada en la tribuna (Four Minute Men), y la publicidad directa en el país y en el extranjero. [1]\n\nCon las experiencias y observaciones de estos vendedores de guerra, narradas y desarrolladas de diversas maneras a lo largo de la década de 1920 ((Lippmann, Public Opinion, The Phantom Public, Bernays, Propaganda, Crystallizing Public Opinion, Creel, How We Advertised America, Lasswell, Propaganda and the World War)), junto con la influencia de sus colegas de la élite y asociados; el optimismo de los jóvenes publicistas concerniente a la manipulación de la democracia popular por la opinión pública, tuvo su fuente con la comprensión de que la opinión pública era en realidad mucho más susceptible a la persuasión de lo que se creía previamente. Las soluciones propuestas para garantizar algo parecido a la democracia en un mundo cada vez más confuso, sentó el “objetivo” en el periodismo, guiado por la inteligencia organizada (Lippmann) y la propaganda, o lo que Edward Bernays calificó de “relaciones públicas”.\n\nEl argumento expuesto en “la Opinión Pública”, de Lippman fue motivado en parte por el rechazo del Senado de Estados Unidos a ser miembro de la Sociedad de Naciones. Un asesor de la administración de Wilson, una figura central detrás de la recolección de inteligencia que informó de la dinámica geopolítica de la posguerra establecidos en la Conferencia de Paz de París, y de los primeros miembros del Consejo de Relaciones Exteriores; Lippmann, considera cada vez más la democracia popular plagada por una irremediablemente mal informada opinión pública incapaz de comprender la creciente complejidad de la sociedad moderna. Sólo los expertos podrían encargarse de evaluar, comprender y actuar con el conocimiento otorgado a través de sus respectivas profesiones y campos.\n\nEn este sentido, el periodismo debería imitar las entonces incipientes ciencias sociales aplicando la objetividad y el aplazamiento a la experiencia de las figuras de autoridad establecidas. Noticias e información podrían ser analizadas, editadas y coordinadas de manera similar para asegurar la exactitud de los periodistas ejerciendo métodos tecnocráticos similares. Aunque Lippmann no especifica exactamente qué organismo se encargaría de supervisar este proceso de “inteligencia organizada,” sus actividades de posguerra proporciona una pista.\n\nLa abogacía de Edward Bernays para con la gestión de la opinión pública es mucho más práctica y manifiesta. Mientras que Lippmann sugiere una democracia regimentada a través de noticias tecnocráticas y el procesamiento de la información; Bernays subraya la manipulación abierta sobre de “cómo la población interpreta la realidad en sí” por parte de una élite privilegiada. Tal manipulación requiere asociaciones artificiales, figuras y acontecimientos que parecen auténticos y espontáneos. “Cualquier persona u organización depende en última instancia de la aprobación del público”, señala Bernays:\n\n“Y por lo tanto, se enfrentan con el problema de la ingeniería del consentimiento del público a un programa o meta … Rechazamos el autoritarismo o la regimentación del gobierno, pero estamos dispuestos a ser persuadidos por la palabra escrita o hablada. La ingeniería del consenso es la esencia misma del proceso democrático, la libertad de persuadir y sugerir”.“Los líderes democráticos deben desempeñar su papel en la conducción de la opinión pública a través de la ingeniería del consenso con las metas y valores socialmente constructivos. Esta función impone de forma natural sobre ellos la obligación de utilizar los procesos educativos, así como otras técnicas disponibles, para lograr lo más completa comprensión posible. – “Relaciones Públicas”, Bernays. [2]\n\nEscrito en la década de 1950, estas observaciones se hacen especialmente aptas en la segunda mitad del siglo XX, cuando los EE.UU. sean típicamente un agresor importante en los asuntos exteriores (y eventualmente domésticos). Sin embargo, ¿qué quiere decir Bernays por, por ejemplo, “los procesos educativos”? Una indicación puede encontrarse observando su papel central en la promoción del consumo de tabaco, la fluoración del agua municipal, y el derrocamiento del régimen de Arbenz, elegido democráticamente en Guatemala. [3]\n\nDe hecho, una gran cantidad de ejemplos históricos contemporáneos sugieren cómo la “ingeniería del consentimiento” ha sido totalmente calculada -y es totalmente antidemocrática. Donde las crisis que requieren este tipo de relaciones públicas drásticas e inmediatas y medidas militares, son a su vez, el resultado de las políticas y acciones del mismo liderazgo. La provocación social y económica de Estados Unidos llevó al ataque japonés a Pearl Harbor y el incidente del Golfo de Tonkin que precipitó la ocupación militar estadounidense de Vietnam son ejemplos obvios de tales eventos manufacturados.\n\nTécnicas similares son evidentes en los principales asesinatos políticos de la década de 1960, donde hasta hoy se le pide al público a participar en la falsa realidad de que Lee Harvey Oswald fue el único culpable en el asesinato del presidente John F. Kennedy. De hecho, en este caso concreto aparece una abrumadora evidencia que apunta a la participación de la Agencia Central de Inteligencia en la orquestación del asesinato.\n\nEl asesinato del gobierno estadounidense del Dr. Martin Luther King Jr., probablemente el personaje más influyente del público afroamericano del siglo XX, no es objeto de debate, a pesar de haber sido profundamente probado en un tribunal de justicia. [4] Sin embargo, como con Kennedy, es un auténtico logro de las relaciones públicas que gran parte de la población estadounidense es ajeno a las dinámicas más profundas de estos asesinatos políticos que se pasan por alto sistemáticamente o se relata en el discurso público de manera inexacta.\n\nEn este sentido, en el contexto histórico de la Operación Gladio, el atentado de Oklahoma City en el Edificio Federal Murrah, los acontecimientos del 11 de septiembre de 2001, los atentados del 11 de marzo en Madrid y Londres del 07/07/2005, la ingeniería del consenso ha alcanzado nuevas alturas asombrosas en que se utiliza el terrorismo orquestado por el Estado para moldear la opinión pública hacia la aceptación de las operaciones policiales militarizadas, la continua erosión de las libertades civiles y la agresión sostenida contra naciones moderadas de Oriente Medio con el fin de crear un cártel sobre los recursos (escasos) y, políticamente reconfigurar toda una región del mundo.\n\nUna vez más, el público es esencialmente obligado a creer que el extremismo político de una forma u otra es la causa de cada evento; incluso a la luz de cómo la sofisticación y el alcance de los “ataques” a la Ciudad de Oklahoma y NYC, sugieren el trabajo de fuerzas de alto nivel. Si uno ahonda debajo de la narrativa de las relaciones públicas de cada caso, la reciente masacre de Newtown y las bombas en la maratón de Boston parecen tener agendas similares donde el público ha sido deliberadamente engañado de nuevo. Periodistas y académicos convencionales son reticentes a abordar públicamente estos fenómenos por temor a ser llamados “teóricos de la conspiración” y a perder su estatus.\n\nDe hecho, el meme “teoría de la conspiración”, fue una campaña de propaganda emprendida por la CIA a mediados de la década de 1960 para contrarrestar las críticas del informe de la Comisión Warren, que es tal vez tan poco conocida como la Operación Mockingbird, el programa de la CIA, donde cientos de periodistas y editores prestaron activamente sus servicios para difundir desinformación de la Agencia. El efecto global de estas operaciones combinadas ha sido un programa de gran éxito que continúa dando forma a los contornos de la vida política y real estadounidense. [5]\n\nLa condición socio-política actual y la supresión de la democracia popular son triunfos de la técnica de la propaganda moderna. Así, están también de manifiesto en los esfuerzos del estado corporativo para diseñar la conformidad del público hacia cosas tales como los fraudes colosales de los organismos modificados genéticamente que se hacen pasar como “alimento”, tóxicos disfrazados de “medicina”, el estado policial y la “guerra contra el terror” en busca de preservar la “seguridad nacional”.\n\nNotas:\n\nCómo Anunciamos América , Nueva York: Harper and Brothers, 1920 Disponible en [1] Aaron Delwiche, “Propaganda: tiempo de guerra de la propaganda: la Primera Guerra Mundial, el Comité de Información Pública”, consultado en 28 de septiembre 2014 en http://www.propagandacritic.com/articles/ww1.cpi.html ; George Creel,, Nueva York: Harper and Brothers, 1920 Disponible en http://archive.org/details/howweadvertameri00creerich\n\n[2] Edward Bernays, Relaciones Públicas , Norman OK: University of Oklahoma Press, 1952, 159-160.\n\n[3] “You can get practically any ideas accepted”, Bernays , campaña para fluorar el suministro de agua de la ciudad de Nueva York. ”Si los médicos están a favor, el público está dispuesto a aceptarlo, porque un médico es una autoridad para la mayoría de la gente, sin importar lo mucho que sabe o no sabe … Por la ley de los promedios, usted puede encontrar generalmente un individuo en cualquier campo que estará dispuesto a aceptar nuevas ideas y las nuevas ideas luego se infiltrarán en los otros que no lo han aceptado. Christopher Bryson, The Fluoride Deception, Nueva York: Seven Stories Press, 2004, 159.\n\n[4] William F. Pepper, un acto del Estado: La ejecución de Martin Luther King , de Nueva York: Verso, 2003.\n\nSource: http://tonyfdez.blogspot.com/2015/03/propaganda-y-relaciones-sociales.html"

In [18]:
import pandas as pd
df = pd.read_csv('news_csv_filtered.csv', sep = ',', lineterminator = '\n')

In [19]:
df.shape

(2920622, 6)

In [143]:
df.head()

,id,domain,type,url,content,title
0,8118551,www.chron.com,reliable,http://www.chron.com/business/article/Close-10...,1055¼ 1038¼ 1054½ +11½ 1045½ 1060¾ 1044¼ 1060¼...,Close - Houston Chronicle
1,8118552,www.chron.com,reliable,http://www.chron.com/news/crime/article/Police...,"Police: Officer shoots, wounds Tennessee stabb...","Police: Officer shoots, wounds Tennessee stabb..."
2,8118553,newsinfo.inquirer.net,reliable,http://newsinfo.inquirer.net/848315/no-chinese...,Philippine Daily Inquirer / 06:04 AM November ...,No Chinese illegal in Clark raid
3,8118554,people.com,reliable,http://people.com/royals/prince-harry-plays-cr...,Samir Hussein/WireImage \nPrince Harry is gett...,Going to Bat: Prince Harry Plays Cricket in th...
4,8118555,www.huffingtonpost.com,reliable,http://www.huffingtonpost.com/2016/11/18/dolla...,Lucas Jackson / Reuters Traders work on the fl...,"Dollar Charges To 14-Year High, Bond Tantrum I..."

In [22]:
df['content'].iloc[1359448]

'1018¾ 1005¼ 1008½ —2¼ 1015¼ 1016¾ 1004¾ 1008 —2 '

In [23]:
df_new = df.drop(df.index[1359448])

In [24]:
df_new.shape

(2920621, 6)

In [16]:
df_new.head()

,id,domain,type,url,content,title
0,22,theshovel.com.au,satire,http://www.theshovel.com.au/tag/malcolm-turnbu...,"For as long as he can remember, Malcolm Turnbu...",malcolm turnbull satire – The Shovel
1,23,theshovel.com.au,satire,http://www.theshovel.com.au/tag/malcolm-turnbu...,"For as long as he can remember, Malcolm Turnbu...",malcolm turnbull jokes – The Shovel
2,31,theshovel.com.au,satire,http://www.theshovel.com.au/tag/australian-pol...,Senators from the Australian Greens will be st...,Australian political satire – The Shovel
3,32,theshovel.com.au,satire,http://www.theshovel.com.au/tag/comedy-website...,Have you ever stopped and wondered what it wou...,comedy website australia – The Shovel
4,33,clickhole.com,satire,http://www.clickhole.com/article/serendipity-m...,"If you don’t believe in fate, here’s a story t...",Serendipity: This Man Made Up An Entire Person...

In [25]:
df_new.to_csv('news_csv_filtered.csv', sep = ',', index = False)